spring:
  application:
    name: Song service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/song-db}
    username: ${SPRING_DATASOURCE_USERNAME:song}
    password: ${SPRING_DATASOURCE_PASSWORD:song_secret}
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URI:http://localhost:8761/eureka}
    register-with-eureka: true