spring:
  application:
    name: Resources service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/resource-db}
    username: ${SPRING_DATASOURCE_USERNAME:resource}
    password: ${SPRING_DATASOURCE_PASSWORD:resource_secret}
services:
  songs:
    base_uri: ${SONG_SERVICE_URI:http://localhost:8081/songs}
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URI:http://localhost:8761/eureka}
    register-with-eureka: true
